### ISSUE TITLE
Show list of products

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#1]
## Value statement

**As a** product seeker
**I need**  a list of all the things I can borrow
**so that** I can see what someone else has available, that I don't need to purchase

## Description (Text, Scribble, Wireframe, Design)

- Showing a list of products available in Hamburg to borrow
![Screen Shot 2020-07-02 at 10 11 10 AM](https://user-images.githubusercontent.com/65187999/86453756-93872e80-bd1e-11ea-9857-ac0833754f00.png)

![Issue #2: Create Product List](https://user-images.githubusercontent.com/65187999/86453256-c7158900-bd1d-11ea-94ba-7cfb94733f74.jpg)

## Acceptance criteria

- [x] all products are listed in vertical direction
- [x] header with logo is fixed
- [x] page is scrollable
- [x] the name, the location and the owner for each product are shown

## Tasks

- [x] Add title
- [x] Create feature branch
- [x] create .json with mock-data
- [x] Create list
- [x] Create fixed header with logo
- [x] Create initial styling
- [x] add storybook for product list item and header
- [x] write component tests

## Size
medium
