### ISSUE TITLE
Add 404 Page and Route

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#10]
## Value statement

**As a** app user
**I need**  a way to get back to the main page, if I have accidently caused an error
**so that**  I can resume using the app

## Description (Text, Scribble, Wireframe, Design)
- Have 404 Page and Route with link back to home
<img width="390" alt="Screen Shot 2020-07-20 at 16 57 32 PM" src="https://user-images.githubusercontent.com/65187999/87952526-358e7100-caaa-11ea-83e1-072565292db9.png">

## Acceptance criteria

- [x] 404 page shows, when user goes to undefined route
- [x] link on 404 page takes the user back to main page

## Tasks

- [x] create component of 404-page
- [x] create routing

## Size
small
