### ISSUE TITLE
Add new product

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#11]
## Value statement

**As a** product offerer
**I need**  to easily add new products to a database
**so that**  product seekers can instantly see what there is available to borrow

## Description (Text, Scribble, Wireframe, Design)

- have a new page, with input fields to add a new product

<img width="798" alt="Screen Shot 2020-07-28 at 10 55 28 AM" src="https://user-images.githubusercontent.com/65187999/88642604-fc18bf80-d0c0-11ea-873f-4201880f6851.png">

## Acceptance criteria

- [x] when clicking on 'add new product' the user will  be taken to the add-product-page
- [x] on add-product-page all input fields are visible
- [x] submit button is disabled when not all required fields are filled in
- [x] submit button creates new item in product list and shows the user a visual feedback, that the new entry has been created
- [x] when not all required fields are filed, the submit button cannot be clicked
- [x] the newly added product is associated with the logged in user

## Tasks

- [x] setup database in firestore to store the product data
- [x] create new components: add-product-page, add-product-form
- [x] add routing to get to add-product-page
- [x] write storybook for form
- [x] style form

## Size
big
