### ISSUE TITLE
Product detail

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#2]
## Value statement

**As a** product seeker
**I need**  a need a detailed description of the product and the contact details 
**so that** I can decide whether the picked product is what I need

## Description (Text, Scribble, Wireframe, Design)

- A product detail page with a 'back' button to got back to product list
<img width="576" alt="Product Detail" src="https://user-images.githubusercontent.com/65187999/86518848-008ce800-be35-11ea-9b47-e33da0e8e817.png">

## Acceptance criteria

- [x] the right product is shown, when clicked on in the list
- [x] page is scrollable if content does not fit on one screen
- [x] the details for each product are shown with full description and contact possibility
- [x] possibility to go back to product list

## Tasks

- [x] add link from each product in list to go to product detail page
- [x] create new page for product detail
- [x] add styling
- [x] add header
- [x] component tests

## Size
medium
