### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#3]
## Tasks

- [x] Create React App
- [x] Delete unused initial content from React App
- [x] Configure package.json
- [x] Add .gitignore
- [x] Add .prettierrc
- [x] Install: Storybook, Styled Components
- [x] Define Global Styles
- [x] Connect to remote git repo

## Size

small
