### ISSUE TITLE
Search for products

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#4]
## Value statement

**As a** product seeker
**I need**  to be able to search for a specific product by name
**so that** I can quickly find the desired product I need

## Description (Text, Scribble, Wireframe, Design)

- Have a search input field above the product list
![Product Search](https://user-images.githubusercontent.com/65187999/87654783-b28eb300-c757-11ea-81d8-e57ac2756b2a.png)

## Acceptance criteria

- [x] when clicking on the magnifier icon, a search input field appears
- [x] the field can be clicked in to start typing
- [x] when pressing enter of the 'search'-icon, the search executes and only the products, which contain the typed word in the product name will show
- [x] when clicking on 'show all' (or X), all products will show and the search bar will disappear
- [x] reloading the page will always show all products again

## Tasks

- [x] add input field on top
- [x] add 'search'-icon and link to show 'all products'
- [x] style input area
- [x] define how to filter array for search results
- [x] write storybook
- [x] write component tests

## Size
medium

**Comment by mar-zim** [comment]
## Value statement

**As a** product seeker
**I need**  to be able to search for a specific product by name
**so that** I can quickly find the desired product I need

## Description (Text, Scribble, Wireframe, Design)

- Have a search input field above the product list

## Acceptance criteria

- [ ] when scrolling to the top of the list, a search input field appears
- [ ] the field can be clicked in to start typing
- [ ] when pressing enter of the 'search'-icon, the search executes and only the products, which contain the typed word in the product name will show
- [ ] when clicking on 'show all', all products will show
- [ ] reloading the page will always show all products again

## Tasks

- [ ] add input field on top
- [ ] add 'search'-icon and link to show 'all products'
- [ ] style input area, so that it only appears when scrolling to the top
- [ ] define search parameters
- [ ] add header

## Size
medium
