### ISSUE TITLE
Setup authentication with firebase

### ISSUE THREAD

**Issue by mar-zim** [mar-zim/capstone-project#7]
## Value statement

**As a** product seeker and product offerer
**I need**  a profile where I can store my contact and personal information
**so that**  other users can find and contact me

## Description (Text, Scribble, Wireframe, Design)
![IMG_20200722_120046](https://user-images.githubusercontent.com/65187999/88163825-866da900-cc13-11ea-8f94-a77dacf4fcb9.jpg)

- Have a login page
- on login page also have the possibility to register if a new user wants to register
- user needs to see whether logged in or not

## Acceptance criteria

- [x] login page shows when opening the page
- [x] login page shows 'Register' option
- [x] login working for registered users
- [x] if user is not registered and not logged in the list with products will not show
- [x] registration only possible when 2 identical passwords
- [x] user gets feedback on erros and login/registration status

## Tasks

- [x] setup project in firebase
- [x] setup authentication with firebase
- [x] create components for loginpage, registerpage
- [x] validate user input in forms
- [x] error handling for async functions
- [x] create storybook for new components
- [x]  add propTypes to new components

## Size
big
